services:
  # Service de base de données PostgreSQL
  db:
    image: postgres:15
    container_name: nexus_db
    restart: always
    volumes:
      # Stockage persistant des données de la DB
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nexus_user
      - POSTGRES_PASSWORD=nexus_password
      - POSTGRES_DB=nexus_sign_db
    ports:
      - "5433:5432"

  # Service de l'application FastAPI
  backend:
    build: .
    container_name: nexus_backend
    ports:
      - "8000:8000"
    volumes:
      # Synchronisation du code local avec le conteneur (pour le développement)
      - .:/code
    environment:
      # URL de connexion à la base de données (utilise le nom du service 'db')
      - DATABASE_URL=postgresql://nexus_user:nexus_password@db:5432/nexus_sign_db
    depends_on:
      - db

# Définition du volume pour la persistance des données
volumes:
  postgres_data: